# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

resources:
  pipelines:
    - pipeline: buildPipeline
      source: finapi_harris_deploy
      trigger:
        branches:
          include:
            - main

variables:
  - group: LogAnalyticsSecrets


pool:
   name: student-lab-pool

steps:


  - script: |
      python -m pip install --upgrade pip
      pip install pytest requests
    displayName: "Install dependencies"

  - script: |
      export LOG_ANALYTICS_WORKSPACE_ID=$(LOG_ANALYTICS_WORKSPACE_ID
      export LOG_ANALYTICS_SHARED_KEY=$(LOG_ANALYTICS_SHARED_KEY)
      pytest -s tests/smoke_tests_centralized.py --junitxml=smoke-results.xml
    displayName: "Run full smoke test suite"

  - task: PublishTestResults@2
    condition: always()   
    inputs:
      testResultsFiles: 'smoke-results.xml'
      testRunTitle: 'Post-deployment Smoke Test'
      failTaskOnFailedTests: true